package com.activeai.integration.banking.api.constants;

public final class PropertyConstants {

  public static final String CASA_ACCOUNT_DETAILS_API_END_POINT = "CASA_ACCOUNT_DETAILS_API_END_POINT";
  public static final String CASA_ACCOUNT_API_END_POINT = "CASA_ACCOUNT_API_END_POINT";
  public static final String LOAD_TESTING_USER_PREFIX = "TEST_USER";
  public static final String CASA_ACCOUNT_TRANSACTIONS_HISTORY_API_END_POINT = "CASA_ACCOUNT_TRANSACTIONS_HISTORY_API_END_POINT";
  public static final String CASA_ACCOUNT_BALANCE_API_END_POINT = "CASA_ACCOUNT_BALANCE_API_END_POINT";
  public static final String CUSTOMER_PROFILE_API_END_POINT = "CUSTOMER_PROFILE_API_END_POINT";
  public static final String CREDIT_CARDS_API_END_POINT = "CREDIT_CARDS_API_END_POINT";
  public static final String CREDIT_CARD_DETAILS_API_END_POINT = "CREDIT_CARD_DETAILS_API_END_POINT";
  public static final String CREDIT_CARD_TRANSACTIONS_HISTORY_API_END_POINT = "CREDIT_CARD_TRANSACTIONS_HISTORY_API_END_POINT";
  public static final String BLOCK_CARD_DETAILS_API_END_POINT = "BLOCK_CARD_DETAILS_API_END_POINT";
  public static final String ACTIVATE_CARD_DETAILS_API_END_POINT = "ACTIVATE_CARD_DETAILS_API_END_POINT";
  public static final String CUSTOMER_LOGIN_API_END_POINT = "CUSTOMER_LOGIN_API_END_POINT";
  public static final String REGISTERED_BILLERS_API_ENDPOINT = "REGISTERED_BILLERS_API_ENDPOINT";
  public static final String BILLER_DETAILS_API_ENDPOINT = "BILLER_DETAILS_API_ENDPOINT";
  public static final String BILL_PAYMENT_API_ENDPOINT = "BILL_PAYMENT_API_ENDPOINT";
  public static final String CARD_PAYMENT_API_ENDPOINT = "CARD_PAYMENT_API_ENDPOINT";
  public static final String CREDIT_CARD_BALANCE_API_END_POINT = "CREDIT_CARD_BALANCE_API_END_POINT";
  public static final String PAYEES_API_END_POINT = "PAYEES_API_END_POINT";
  public static final String TRANSFER_CONFIRM_API_END_POINT = "TRANSFER_CONFIRM_API_END_POINT";
  public static final String DEBIT_CARD_LIMIT_API_END_POINT = "DEBIT_CARD_LIMIT_API_END_POINT";
  public static final String CREDIT_CARD_LIMIT_API_END_POINT = "CREDIT_CARD_LIMIT_API_END_POINT";
  public static final String DEBIT_CARD_LIMIT_CONFIRM_API_ENDPOINT ="DEBIT_CARD_LIMIT_CONFIRM_API_ENDPOINT";
  public static final String DEBIT_CARDS_API_END_POINT = "DEBIT_CARDS_API_END_POINT";
  public static final String DEBIT_CARD_DETAILS_API_END_POINT = "DEBIT_CARD_DETAILS_API_END_POINT";
  public static final String DEPOSIT_ACCOUNT_API_END_POINT="DEPOSIT_ACCOUNT_API_END_POINT";
  public static final String CREDIT_CARD_LIMIT_CONFIRM_API_ENDPOINT="CREDIT_CARD_LIMIT_CONFIRM_API_ENDPOINT";
  public static final String RESET_PIN_CONFIRM_API_ENDPOINT = "RESET_PIN_CONFIRM_API_ENDPOINT";
  public static final String LOAN_ACCOUNT_API_END_POINT="LOAN_ACCOUNT_API_END_POINT";
  public static final String DEPOSIT_ACCOUNT_DETAILS_API_END_POINT="DEPOSIT_ACCOUNT_DETAILS_API_END_POINT";
  public static final String LOAN_ACCOUNT_DETAILS_API_END_POINT="LOAN_ACCOUNT_DETAILS_API_END_POINT";
  public static final String LOAN_ACCOUNT_BALANCE_API_END_POINT="LOAN_ACCOUNT_BALANCE_API_END_POINT";
  public static final String DEPOSIT_ACCOUNT_BALANCE_API_END_POINT="DEPOSIT_ACCOUNT_BALANCE_API_END_POINT";
  public static final String REPLACE_CARD_CONFIRM_API_ENDPOINT = "REPLACE_CARD_CONFIRM_API_ENDPOINT";
  public static final String NOMINEE_API_END_POINT="NOMINEE_API_END_POINT";
  public static final String DEPOSIT_PLAN_API_END_POINT="DEPOSIT_PLAN_API_END_POINT";
  public static final String OPEN_FD_API_END_POINT="OPEN_FD_API_END_POINT";
  public static final String INTERNATIONAL_USAGE_API_END_POINT="INTERNATIONAL_USAGE_API_END_POINT";
  public static final String INTERNATIONAL_USAGE_ENABLED_API_END_POINT="INTERNATIONAL_USAGE_ENABLED_API_END_POINT";
  public static final String UPDATE_EMAIL_API_END_POINT="UPDATE_EMAIL_API_END_POINT";
  public static final String UPDATE_PHONE_API_END_POINT="UPDATE_PHONE_API_END_POINT";
  public static final String UPDATE_ADDRESS_API_END_POINT="UPDATE_ADDRESS_API_END_POINT";
  public static final String CHEQUE_BOOK_ORDER_CONFIRM_API_ENDPOINT="CHEQUE_BOOK_ORDER_CONFIRM_API_ENDPOINT";
  public static final String ATM_LOCATOR_ADDRESS_API_END_POINT="ATM_LOCATOR_ADDRESS_API_END_POINT";
  public static final String ATM_LOCATOR_GEOCODES_API_END_POINT="ATM_LOCATOR_GEOCODES_API_END_POINT";
  public static final String CONVERT_EMI_API_ENDPOINT = "CONVERT_EMI_API_ENDPOINT";
  public static final String CONVERT_EMI_CONFIRM_API_ENDPOINT = "CONVERT_EMI_CONFIRM_API_ENDPOINT";
  public static final String ONE_TIME_TRANSFER_API_END_POINT ="ONE_TIME_TRANSFER_API_END_POINT";
  public static final String ONE_TIME_TRANSFER_PAYEE_VALIDATION_API_END_POINT = "ONE_TIME_TRANSFER_PAYEE_VALIDATION_API_END_POINT";


  private PropertyConstants(){
    //To hide implementation details
  }
}
