package com.activeai.integration.banking.constants;

public interface PropertyConstants {
  String ACCOUNT_DETAILS_API_END_POINT = "ACCOUNT_DETAILS_API_END_POINT";
  String ACCOUNTS_API_END_POINT = "ACCOUNTS_API_END_POINT";
  String ACCOUNT_TRANSACTIONS_HISTORY_API_END_POINT = "ACCOUNT_TRANSACTIONS_HISTORY_API_END_POINT";
  String ACCOUNT_BALANCE_API_END_POINT = "ACCOUNT_BALANCE_API_END_POINT";
  String CUSTOMER_PROFILE_API_END_POINT = "CUSTOMER_PROFILE_API_END_POINT";
  String CARDS_API_END_POINT = "CARDS_API_END_POINT";
  String CARD_DETAILS_API_END_POINT = "CARD_DETAILS_API_END_POINT";
  String CARDS_TRANSACTIONS_HISTORY_API_END_POINT = "CARDS_TRANSACTIONS_HISTORY_API_END_POINT";
  String BLOCK_CARD_DETAILS_API_END_POINT = "BLOCK_CARD_DETAILS_API_END_POINT";
  String CUSTOMER_LOGIN_API_END_POINT = "CUSTOMER_LOGIN_API_END_POINT";
  String REGISTERED_BILLERS_API_ENDPOINT = "REGISTERED_BILLERS_API_ENDPOINT";
}
