package com.activeai.integration.banking.constants;

public interface PropertyConstants {
  String ACCOUNT_DETAILS_API_END_POINT = "ACCOUNT_DETAILS_API_END_POINT";
  String ACCOUNTS_API_END_POINT = "ACCOUNTS_API_END_POINT";
  String ACCOUNT_TRANSACTIONS_HISTORY_API_END_POINT = "ACCOUNT_TRANSACTIONS_HISTORY_API_END_POINT";
  String ACCOUNT_BALANCE_API_END_POINT = "ACCOUNT_BALANCE_API_END_POINT";
  String CUSTOMER_PROFILE_API_END_POINT = "CUSTOMER_PROFILE_API_END_POINT";
  String CREDIT_CARDS_API_END_POINT = "CREDIT_CARDS_API_END_POINT";
  String CREDIT_CARD_DETAILS_API_END_POINT = "CREDIT_CARD_DETAILS_API_END_POINT";
  String CREDIT_CARD_TRANSACTIONS_HISTORY_API_END_POINT = "CREDIT_CARD_TRANSACTIONS_HISTORY_API_END_POINT";
  String BLOCK_CARD_DETAILS_API_END_POINT = "BLOCK_CARD_DETAILS_API_END_POINT";
  String ACTIVATE_CARD_DETAILS_API_END_POINT = "ACTIVATE_CARD_DETAILS_API_END_POINT";
  String CUSTOMER_LOGIN_API_END_POINT = "CUSTOMER_LOGIN_API_END_POINT";
  String REGISTERED_BILLERS_API_ENDPOINT = "REGISTERED_BILLERS_API_ENDPOINT";
  String BILLER_DETAILS_API_ENDPOINT = "BILLER_DETAILS_API_ENDPOINT";
  String BILL_PAYMENT_API_ENDPOINT = "BILL_PAYMENT_API_ENDPOINT";
  String CREDIT_CARD_BALANCE_API_END_POINT = "CREDIT_CARD_BALANCE_API_END_POINT";
  String PAYEES_API_END_POINT = "PAYEES_API_END_POINT";
  String TRANSFER_CONFIRM_API_END_POINT = "TRANSFER_CONFIRM_API_END_POINT";
  String DEBIT_CARD_LIMIT_API_END_POINT = "DEBIT_CARD_LIMIT_API_END_POINT";
  String DEBIT_CARD_LIMIT_CONFIRM_API_ENDPOINT ="DEBIT_CARD_LIMIT_CONFIRM_API_ENDPOINT";
  String DEBIT_CARDS_API_END_POINT = "DEBIT_CARDS_API_END_POINT";
  String DEBIT_CARD_DETAILS_API_END_POINT = "DEBIT_CARD_DETAILS_API_END_POINT";
  String DEBIT_CARD_BALANCE_API_END_POINT = "DEBIT_CARD_BALANCE_API_END_POINT";
  String DEBIT_CARD_TRANSACTIONS_HISTORY_API_END_POINT = "DEBIT_CARD_TRANSACTIONS_HISTORY_API_END_POINT";
}
