package com.activeai.integration.banking.constants;

public interface PropertyConstants {
  String ACCOUNT_DETAILS_API = "ACCOUNT_DETAILS_API";
  String ACCOUNTS_API_URL = "ACCOUNTS_API_URL";
  String ACCOUNT_TRANSACTIONS_HISTORY_API = "ACCOUNT_TRANSACTIONS_HISTORY_API";
  String ACCOUNT_BALANCE_API = "ACCOUNT_BALANCE_API";
  String SUCESS_LOGIN_API_RESPONSE = "SUCESS_LOGIN_API_RESPONSE";
}
